variables:
  APOLLO_FAT: "http://admin:123456@10.11.101.196:9999/fat"
  APOLLO_PROD: "http://admin:123456@10.11.101.196:9999/prod"

test build:
  image: golang:1.14
  stage: build
  script:
    # 实际使用过程，请把 $CI_COMMIT_REF_NAME $CI_PROJECT_ID 传到 dockerfile中，打包到镜像里
    - export APOLLO=$APOLLO_FAT
    - go mod vendor
    - go run main.go
  only:
    - test

prod build:
  image: golang:1.14
  stage: build
  script:
    # 实际使用过程，请把 $CI_COMMIT_REF_NAME $CI_PROJECT_ID 传到 dockerfile中，打包到镜像里
    - export APOLLO=$APOLLO_PROD
    - go mod vendor
    - go run main.go
  only:
    - master

test apollo proxy trigger:
  stage: deploy
  image: golang:1.14
  script:
    - echo 'trigger from apollo'
  only:
    refs:
      - test
    variables:
      - $TRIGGER == 'apollo-proxy'

prod apollo proxy trigger:
  stage: deploy
  image: golang:1.14
  script:
    - echo 'trigger from apollo'
  only:
    refs:
      - master
    variables:
      - $TRIGGER == 'apollo-proxy'
